language: minimal

services:
  - docker

env:
  global:
    - DOCKER_ORG_NAME=tidair
    - DOCKER_REPO=smurf2mce-base

stages:
  - name: deploy_docker
    if: tag IS present

jobs:
  include:
    - stage: deploy_docker
      name: "Deploy Docker Image"
      before_script:
        # Use the git tag to tag tag docker image
        - export DOCKER_TAG=`git describe --tags --always`
        # Login to docker
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ORG_NAME}" --password-stdin;

      script:
        # Build the docker image
        - docker build -t ${DOCKER_ORG_NAME}/${DOCKER_REPO} .

      after_success:
        # Upload docker image (as tagged and latest version)
        - docker push ${DOCKER_ORG_NAME}/${DOCKER_REPO};
        - docker tag ${DOCKER_ORG_NAME}/${DOCKER_REPO} ${DOCKER_ORG_NAME}/${DOCKER_REPO}:${DOCKER_TAG};
        - docker push ${DOCKER_ORG_NAME}/${DOCKER_REPO}:${DOCKER_TAG};
        - echo "Docker image '${DOCKER_ORG_NAME}/${DOCKER_REPO}:${DOCKER_TAG}' pushed"

notifications:
  slack:
    secure: MS7yMpNUte9DX0FFFxE0fIH9tX1/7+u7oG9PcLYqL+VLiN/4s3w7guxu9WNjUN91XMDQeUsgyq1662Kkk8+U6+BZadZbMXRxht3AbzOk0A962NW873G8ghZYsHSelYRMMo8b6RuYTe1TO8oDYByHuEiFtD9+iqUVEizbublqWi7AxOpcOcF23ggG37/tXS4WbL1PWRprJ7YQ+riDokU4oKqbdtzJssOHS4AzgfGDaGiipTj0WhcaDvnMiTkINf3Md6XZKs610ovC1XPeEZfd71WFXzwD7xNEEsLNrrOi0D2djgp+XeFUpbWsM8GfYFkZHtHAgR9mA7bDceRpvKFnIQJ0dBLKwh4UuFGX14yIMC/DLPGYaZR01kA8PPQn/B3TpQS1aS86PuiqJqudib/MemTTd01kspWTnIcQvklkl0TqPasDAbYBi5qcVVYcDrdUf+MG2IKJu9F2DZ/jRgT8K+ld3Z66/Z6YaqzT09pdarSajRSWE523LkgX3wpvmYZe6eqOxd3ZvcVagKdxs4JLh5cK/eMFfvrJwxRQVwiHLGEkdI+NqFAATQiyx9G6dXVl+FZx98eRlcsCtm1EcoZthQgHUZA68a0iMu3bfvyRo3jQTJT3sHGokZ3dIa+WUzVBIi+zu5k8d3ptbi/MFrDcxSmC1q3qBNnVeJNxjg2BhvM=
